version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: barbershop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    command: python manage.py collectstatic --noinput
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: 9d4#+**cl85%3zw0019s89j-*sfum1*o6mo((mq%caxd3cdyv3
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: barbershop
      DB_HOSTNAME: postgres
      DB_PORT: 5432
    depends_on:
      - postgres